server:
  address: localhost
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #globally_quoted_identifiers: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug